version: '3'

services:

  server:
    volumes:
      - static:/static
      - ./server/:/usr/src/app/
    env_file:
      - ./env/.env
    build: ./server
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  celery:
    build: ./server
    command: celery -A core worker -l info
    volumes:
      - ./server/:/usr/src/app/
    depends_on:
      - server

  celery-beat:
    build: ./server
    command: celery -A core beat -l info
    volumes:
      - ./server/:/usr/src/app/
    depends_on:
      - server

  client:
    build: ./client
    volumes:
      - dist:/client/dist/

  nginx:
    build: ./nginx
    volumes:
      - dist:/client/dist/
      - static:/static
      - ./data/certbot/letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/html
    depends_on:
      - server
      - client
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:6-alpine

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.db

volumes:
  dist:
  static:
  postgres_data:
  certbot_challenges:
  

