version: '3'

services:

  server:
    volumes:
      - static:/static
    env_file:
      - .env
    build: ./server
    ports:
      - "8000:8000"
    restart: always


  client-nginx:
    build: .
    volumes:
      - static:/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - server
      - client-nginx

volumes:
  static:

