version: '3'

services:

  server:
    volumes:
      - static:/static
      - ./server/:/usr/src/app/
    env_file:
      - .env
    build: ./server
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  celery:
    build: ./server
    command: celery -A core worker -l info
    volumes:
      - ./server/:/usr/src/app/
    depends_on:
      - server

  celery-beat:
    build: ./server
    command: celery -A core beat -l info
    volumes:
      - ./server/:/usr/src/app/
    depends_on:
      - server

  client:
    build: ./client
    volumes:
      - ./client/dist/:/client/dist/

  nginx:
    build: ./nginx
    volumes:
      - ./client/dist/:/client/dist/
      - static:/static
      - certbot_challenges:/var/www/.well-known/acme-challenge
      - ./certbot/conf/:/etc/nginx/ssl/
    depends_on:
      - server
      - client
    ports:
      - 80:80
      - 443:443

  # client-nginx:
  #   build: .
  #   volumes:
  #     - static:/static
  #     - ./certbot/www:/var/www/certbot/
  #     - ./certbot/conf/:/etc/nginx/ssl/
  #   depends_on:
  #     - server
  #   ports:
  #     - "80:80"
  #     - "443:443"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - certbot_challenges:/var/www/.well-known/acme-challenge
      - ./certbot/conf/:/etc/letsencrypt/
    depends_on:
      - server
      - client
      - nginx

  redis:
    image: redis:6-alpine

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  static:
  postgres_data:
  certbot_challenges:
  

