version: '3'

services:

  server:
    volumes:
      - static:/static
    env_file:
      - .env
    build: ./server
    command: celery worker --app=core --loglevel=info
    ports:
      - "8000:8000"
    depends_on:
      - redis

  client-nginx:
    build: .
    volumes:
      - static:/static
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    depends_on:
      - server
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
    depends_on:
      - server
      - client-nginx

  redis:
    image: redis:6-alpine

volumes:
  static:

